config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  devise_for :users

   

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
      <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>
    
</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Instagram", root_url, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to "New Post", new_post_path %>
                    </li>
                    <% if current_user %>
                        <li>
                            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                        </li>
                    <% else %>
                    <li>
                        <%= link_to "Login", new_user_session_path %>
                    </li>
                    
                    <li>
                        <%= link_to "Register", new_user_registration_path %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    
    
    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <% flash.each do |a, b| %>
                <div class="alert alert-success"> <%= b %></div>
                <% end %>
                <%= yield %>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <center>

    </center>

</body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>New Post</h1>
<hr>

<%= form_for @post do |f| %>
  <%= f.label :description %>
  <%= f.text_area :description %><br />

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>